import puppeteer from '/root/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js';
const b = await puppeteer.launch({headless:true, executablePath:'/usr/bin/chromium', args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p = await b.newPage();
await p.setViewport({width:1600,height:1000});
await p.goto('file:///root/caesar3d/roma.html',{waitUntil:'load'});
await new Promise(r=>setTimeout(r,1200));
await p.evaluate(()=>{ document.getElementById('intro').style.display='none';
  setSpeed(8); for(let i=0;i<1200;i++){simTick(0.16); updateCarts(0.06);} setSpeed(1);
  cam.tx=0; cam.tz=8; cam.dist=40; cam.pitch=0.55; cam.yaw=0.4;
  setTool('ironMine'); showPaths=true; chainOpen=true; renderChains();
  msg('Clay Pit has no water supply nearby','bad'); msg('A domus grew into a Mansion!','good');
  sel=blds.find(b=>b.type==='house'); if(sel){sel.tier=3; bldGroup.remove(sel.mesh); sel.mesh=houseMesh(3); placeGroup(sel);} refreshSel(); });
await new Promise(r=>setTimeout(r,2500));
await p.screenshot({path:'s6_full.png'});
await b.close();
