import puppeteer from '/root/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js';
const b = await puppeteer.launch({headless:true, executablePath:'/usr/bin/chromium', args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p = await b.newPage();
await p.setViewport({width:1600,height:1000});
p.on('pageerror',e=>console.log('ERR',e.stack));
p.on('console',m=>{ if(m.type()==='error') console.log('CON',m.text().slice(0,200)); });
await p.goto('file:///root/caesar3d/roma.html',{waitUntil:'load'});
await new Promise(r=>setTimeout(r,1200));
await p.screenshot({path:'s1_intro.png'});
await p.evaluate(()=>{ document.getElementById('intro').style.display='none';
  cam.tx=0; cam.tz=10; cam.dist=44; cam.pitch=0.58; cam.yaw=0.45; });
await new Promise(r=>setTimeout(r,1200));
await p.screenshot({path:'s2_city.png'});
await p.evaluate(()=>{ chainOpen=true; renderChains(); sel=blds.find(b=>b.type==='house'); refreshSel(); });
await new Promise(r=>setTimeout(r,600));
await p.screenshot({path:'s3_ui.png'});
await p.evaluate(()=>{ soilOverlay.visible=true; cam.dist=22; cam.pitch=0.45; cam.tx=2; cam.tz=14; });
await new Promise(r=>setTimeout(r,1000));
await p.screenshot({path:'s4_soil.png'});
await p.evaluate(()=>{ soilOverlay.visible=false; cam.dist=13; cam.pitch=0.34; cam.tx=0; cam.tz=6; showPaths=true; });
await new Promise(r=>setTimeout(r,900));
await p.screenshot({path:'s5_close.png'});
await b.close();
